//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.net_Mvc_Crud_Entityframework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
}
